package net.exylia.lib.api.sandbox;

/**
 * Where a sandbox world's terrain came from.
 *
 * @since 1.0.0
 */
public enum WorldType {

    /** Generated by the sandbox, and deleted with it. */
    MANAGED,

    /** An existing world folder the sandbox was pointed at and does not own. */
    IMPORTED
}
